--
-- PostgreSQL database dump
--

\restrict sbLr80DozPdCDfQXVk4soq7yuxR1O0nybYrbzgYmcsqvpi6OwVmrP3RqmPgW4oj

-- Dumped from database version 15.15 (Debian 15.15-1.pgdg13+1)
-- Dumped by pg_dump version 15.15 (Debian 15.15-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO customlab_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO customlab_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO customlab_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO customlab_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO customlab_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO customlab_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caracteristica_producto; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.caracteristica_producto (
    id_caracteristica integer NOT NULL,
    id_producto integer NOT NULL
);


ALTER TABLE public.caracteristica_producto OWNER TO customlab_user;

--
-- Name: caracteristicas; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.caracteristicas (
    id_caracteristica integer NOT NULL,
    caracteristica character varying(200) NOT NULL
);


ALTER TABLE public.caracteristicas OWNER TO customlab_user;

--
-- Name: caracteristicas_id_caracteristica_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

CREATE SEQUENCE public.caracteristicas_id_caracteristica_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.caracteristicas_id_caracteristica_seq OWNER TO customlab_user;

--
-- Name: caracteristicas_id_caracteristica_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: customlab_user
--

ALTER SEQUENCE public.caracteristicas_id_caracteristica_seq OWNED BY public.caracteristicas.id_caracteristica;


--
-- Name: carrito; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.carrito (
    id_usuario integer NOT NULL,
    id_producto integer NOT NULL,
    id_talla integer NOT NULL,
    cantidad integer NOT NULL,
    precio_total numeric(10,2) NOT NULL
);


ALTER TABLE public.carrito OWNER TO customlab_user;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO customlab_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO customlab_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO customlab_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO customlab_user;

--
-- Name: imagenes_productos; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.imagenes_productos (
    id_imagen_producto integer NOT NULL,
    id_producto integer NOT NULL,
    ruta character varying(300) NOT NULL
);


ALTER TABLE public.imagenes_productos OWNER TO customlab_user;

--
-- Name: imagenes_productos_id_imagen_producto_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

CREATE SEQUENCE public.imagenes_productos_id_imagen_producto_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.imagenes_productos_id_imagen_producto_seq OWNER TO customlab_user;

--
-- Name: imagenes_productos_id_imagen_producto_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: customlab_user
--

ALTER SEQUENCE public.imagenes_productos_id_imagen_producto_seq OWNED BY public.imagenes_productos.id_imagen_producto;


--
-- Name: imagenes_usuario; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.imagenes_usuario (
    id_imagen_usuario integer NOT NULL,
    id_usuario integer NOT NULL,
    ruta character varying(300) NOT NULL
);


ALTER TABLE public.imagenes_usuario OWNER TO customlab_user;

--
-- Name: imagenes_usuario_id_imagen_usuario_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

CREATE SEQUENCE public.imagenes_usuario_id_imagen_usuario_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.imagenes_usuario_id_imagen_usuario_seq OWNER TO customlab_user;

--
-- Name: imagenes_usuario_id_imagen_usuario_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: customlab_user
--

ALTER SEQUENCE public.imagenes_usuario_id_imagen_usuario_seq OWNED BY public.imagenes_usuario.id_imagen_usuario;


--
-- Name: incidencias; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.incidencias (
    id_incidencia integer NOT NULL,
    id_usuario integer NOT NULL,
    tipo character varying NOT NULL,
    fecha timestamp with time zone NOT NULL,
    estado_incidencia character varying NOT NULL,
    descripcion text NOT NULL
);


ALTER TABLE public.incidencias OWNER TO customlab_user;

--
-- Name: incidencias_id_incidencia_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

CREATE SEQUENCE public.incidencias_id_incidencia_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.incidencias_id_incidencia_seq OWNER TO customlab_user;

--
-- Name: incidencias_id_incidencia_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: customlab_user
--

ALTER SEQUENCE public.incidencias_id_incidencia_seq OWNED BY public.incidencias.id_incidencia;


--
-- Name: pedidos; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.pedidos (
    id_pedido integer NOT NULL,
    id_usuario integer NOT NULL,
    estado character varying NOT NULL,
    total numeric(10,2) NOT NULL,
    fecha timestamp with time zone,
    direccion character varying NOT NULL,
    numero_piso character varying
);


ALTER TABLE public.pedidos OWNER TO customlab_user;

--
-- Name: pedidos_id_pedido_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

CREATE SEQUENCE public.pedidos_id_pedido_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.pedidos_id_pedido_seq OWNER TO customlab_user;

--
-- Name: pedidos_id_pedido_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: customlab_user
--

ALTER SEQUENCE public.pedidos_id_pedido_seq OWNED BY public.pedidos.id_pedido;


--
-- Name: productos; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.productos (
    id_producto integer NOT NULL,
    nombre_producto character varying(150) NOT NULL,
    precio_venta numeric(10,2) NOT NULL,
    precio_original numeric(10,2),
    precio_costo numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    categoria character varying(100) NOT NULL,
    personalizable boolean NOT NULL,
    nuevo boolean NOT NULL,
    oferta boolean NOT NULL
);


ALTER TABLE public.productos OWNER TO customlab_user;

--
-- Name: productos_id_producto_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

CREATE SEQUENCE public.productos_id_producto_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.productos_id_producto_seq OWNER TO customlab_user;

--
-- Name: productos_id_producto_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: customlab_user
--

ALTER SEQUENCE public.productos_id_producto_seq OWNED BY public.productos.id_producto;


--
-- Name: productos_personalizados; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.productos_personalizados (
    id_producto_personalizado integer NOT NULL,
    id_producto integer NOT NULL,
    id_talla integer NOT NULL,
    id_imagen_usuario integer NOT NULL,
    color character varying(10) NOT NULL,
    texto character varying(255) NOT NULL,
    ruta_imagen character varying(100) NOT NULL,
    posicion_xy point DEFAULT point((0)::double precision, (0)::double precision)
);


ALTER TABLE public.productos_personalizados OWNER TO customlab_user;

--
-- Name: productos_personalizados_id_producto_personalizado_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

CREATE SEQUENCE public.productos_personalizados_id_producto_personalizado_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.productos_personalizados_id_producto_personalizado_seq OWNER TO customlab_user;

--
-- Name: productos_personalizados_id_producto_personalizado_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: customlab_user
--

ALTER SEQUENCE public.productos_personalizados_id_producto_personalizado_seq OWNED BY public.productos_personalizados.id_producto_personalizado;


--
-- Name: productos_vendidos; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.productos_vendidos (
    id_producto_vendido integer NOT NULL,
    id_producto integer NOT NULL,
    id_pedido integer NOT NULL,
    id_talla integer NOT NULL,
    beneficio numeric(10,2) NOT NULL,
    cantidad integer NOT NULL,
    precio_venta numeric(10,2) NOT NULL
);


ALTER TABLE public.productos_vendidos OWNER TO customlab_user;

--
-- Name: productos_vendidos_id_producto_vendido_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

CREATE SEQUENCE public.productos_vendidos_id_producto_vendido_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.productos_vendidos_id_producto_vendido_seq OWNER TO customlab_user;

--
-- Name: productos_vendidos_id_producto_vendido_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: customlab_user
--

ALTER SEQUENCE public.productos_vendidos_id_producto_vendido_seq OWNED BY public.productos_vendidos.id_producto_vendido;


--
-- Name: tallas; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.tallas (
    id_talla integer NOT NULL,
    id_producto integer NOT NULL,
    talla character varying(45) NOT NULL,
    stock integer NOT NULL
);


ALTER TABLE public.tallas OWNER TO customlab_user;

--
-- Name: tallas_id_talla_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

CREATE SEQUENCE public.tallas_id_talla_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tallas_id_talla_seq OWNER TO customlab_user;

--
-- Name: tallas_id_talla_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: customlab_user
--

ALTER SEQUENCE public.tallas_id_talla_seq OWNED BY public.tallas.id_talla;


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: customlab_user
--

CREATE TABLE public.usuarios (
    id_usuario integer NOT NULL,
    nombre character varying(100) NOT NULL,
    apellidos character varying(150) NOT NULL,
    password character varying(255) NOT NULL,
    email character varying(150) NOT NULL,
    fecha_nacimiento date,
    doble_factor boolean,
    rol character varying(50) NOT NULL,
    secret_2fa character varying(32)
);


ALTER TABLE public.usuarios OWNER TO customlab_user;

--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: customlab_user
--

CREATE SEQUENCE public.usuarios_id_usuario_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuarios_id_usuario_seq OWNER TO customlab_user;

--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: customlab_user
--

ALTER SEQUENCE public.usuarios_id_usuario_seq OWNED BY public.usuarios.id_usuario;


--
-- Name: caracteristicas id_caracteristica; Type: DEFAULT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.caracteristicas ALTER COLUMN id_caracteristica SET DEFAULT nextval('public.caracteristicas_id_caracteristica_seq'::regclass);


--
-- Name: imagenes_productos id_imagen_producto; Type: DEFAULT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.imagenes_productos ALTER COLUMN id_imagen_producto SET DEFAULT nextval('public.imagenes_productos_id_imagen_producto_seq'::regclass);


--
-- Name: imagenes_usuario id_imagen_usuario; Type: DEFAULT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.imagenes_usuario ALTER COLUMN id_imagen_usuario SET DEFAULT nextval('public.imagenes_usuario_id_imagen_usuario_seq'::regclass);


--
-- Name: incidencias id_incidencia; Type: DEFAULT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.incidencias ALTER COLUMN id_incidencia SET DEFAULT nextval('public.incidencias_id_incidencia_seq'::regclass);


--
-- Name: pedidos id_pedido; Type: DEFAULT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.pedidos ALTER COLUMN id_pedido SET DEFAULT nextval('public.pedidos_id_pedido_seq'::regclass);


--
-- Name: productos id_producto; Type: DEFAULT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.productos ALTER COLUMN id_producto SET DEFAULT nextval('public.productos_id_producto_seq'::regclass);


--
-- Name: productos_personalizados id_producto_personalizado; Type: DEFAULT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.productos_personalizados ALTER COLUMN id_producto_personalizado SET DEFAULT nextval('public.productos_personalizados_id_producto_personalizado_seq'::regclass);


--
-- Name: productos_vendidos id_producto_vendido; Type: DEFAULT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.productos_vendidos ALTER COLUMN id_producto_vendido SET DEFAULT nextval('public.productos_vendidos_id_producto_vendido_seq'::regclass);


--
-- Name: tallas id_talla; Type: DEFAULT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.tallas ALTER COLUMN id_talla SET DEFAULT nextval('public.tallas_id_talla_seq'::regclass);


--
-- Name: usuarios id_usuario; Type: DEFAULT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.usuarios ALTER COLUMN id_usuario SET DEFAULT nextval('public.usuarios_id_usuario_seq'::regclass);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$LjOIZIN4WVXQLv7bzuXbKR$tYday4pUyyQoSQtugngaPutTRHPFhKrggiA0nMwcUMo=	2026-02-26 14:36:11.601269+00	t	customlab_admin			customlab@gmail.com	t	t	2026-02-20 16:49:12.734387+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: caracteristica_producto; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.caracteristica_producto (id_caracteristica, id_producto) FROM stdin;
2	2
3	4
2	5
3	7
2	1
2	9
7	1
8	1
\.


--
-- Data for Name: caracteristicas; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.caracteristicas (id_caracteristica, caracteristica) FROM stdin;
2	Verano
3	Invierno
7	Hecho en España
8	Lino
\.


--
-- Data for Name: carrito; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.carrito (id_usuario, id_producto, id_talla, cantidad, precio_total) FROM stdin;
9	2	4	3	104.97
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	customlab_models	productos
8	customlab_models	pedidos
9	customlab_models	imagenesusuario
10	customlab_models	usuarios
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-10 16:57:46.330192+00
2	auth	0001_initial	2026-02-10 16:57:47.274021+00
3	admin	0001_initial	2026-02-10 16:57:47.507124+00
4	admin	0002_logentry_remove_auto_add	2026-02-10 16:57:47.538264+00
5	admin	0003_logentry_add_action_flag_choices	2026-02-10 16:57:47.570738+00
6	contenttypes	0002_remove_content_type_name	2026-02-10 16:57:47.628606+00
7	auth	0002_alter_permission_name_max_length	2026-02-10 16:57:47.665788+00
8	auth	0003_alter_user_email_max_length	2026-02-10 16:57:47.693242+00
9	auth	0004_alter_user_username_opts	2026-02-10 16:57:47.724648+00
10	auth	0005_alter_user_last_login_null	2026-02-10 16:57:47.74811+00
11	auth	0006_require_contenttypes_0002	2026-02-10 16:57:47.762014+00
12	auth	0007_alter_validators_add_error_messages	2026-02-10 16:57:47.792189+00
13	auth	0008_alter_user_username_max_length	2026-02-10 16:57:47.884843+00
14	auth	0009_alter_user_last_name_max_length	2026-02-10 16:57:47.916683+00
15	auth	0010_alter_group_name_max_length	2026-02-10 16:57:47.952612+00
16	auth	0011_update_proxy_permissions	2026-02-10 16:57:47.976157+00
17	auth	0012_alter_user_first_name_max_length	2026-02-10 16:57:48.008854+00
18	sessions	0001_initial	2026-02-10 16:57:48.206296+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
os1g29d0yvv4qofecbblnr8xezidvjxe	.eJxVjEEOwiAQRe_C2hAgncK4dO8ZyDAMUjU0Ke3KeHdt0oVu_3vvv1Skba1x67LEKauzsur0uyXih7Qd5Du126x5busyJb0r-qBdX-csz8vh_h1U6vVbiwnGkfOCY0YJI2DxAzPYIq4MTOjRFhBDJYlHBnRBbLCegB1kEPX-AOh_OCc:1vtThj:FJQbEDiIQD6-47UNSxlmx0WYsRWL1_rWJbk4gaiiitc	2026-03-06 16:50:11.897051+00
ubfn2cj7lnmsbe9ckp02uqw05bmoxhem	.eJxVjEEOwiAQRe_C2hAgncK4dO8ZyDAMUjU0Ke3KeHdt0oVu_3vvv1Skba1x67LEKauzsur0uyXih7Qd5Du126x5busyJb0r-qBdX-csz8vh_h1U6vVbiwnGkfOCY0YJI2DxAzPYIq4MTOjRFhBDJYlHBnRBbLCegB1kEPX-AOh_OCc:1vvcTL:PzIszosFqfbWiocZWZEIHaB5XjqYv7kxlqGWQleSkOY	2026-03-12 14:36:11.715887+00
\.


--
-- Data for Name: imagenes_productos; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.imagenes_productos (id_imagen_producto, id_producto, ruta) FROM stdin;
1	1	/media/images/products/1/1_vestido_midi_1773933685.png
3	1	/media/images/products/1/1_vestido_midi_3_1773952858.png
4	2	/media/images/products/2/2_camiseta_oversize_1773953342.png
5	2	/media/images/products/2/2_camiseta_oversize_2_1773953342.png
2	1	/media/images/products/1/1_vestido_midi_2_1773933685.png
6	3	/media/images/products/3/3_camiseta_basica_1774042944.png
7	3	/media/images/products/3/3_camiseta_basica_modelos_1774042944.png
8	4	/media/images/products/4/4_sudadera_basica_1776258566.png
9	4	/media/images/products/4/4_sudadera_basica2_1776258566.png
10	5	/media/images/products/5/5_gorra_segarro_1776327825.png
11	5	/media/images/products/5/5_gorra_segarro2_1776327825.png
14	7	/media/images/products/7/7_jersey_america_1776353348.png
15	7	/media/images/products/7/7_jersey_america2_1776353348.png
18	7	/media/images/products/7/7_jersey_america_1777377289.png
22	9	/media/images/products/9/9_nike_tech_gris_nico_1777388817.png
23	9	/media/images/products/9/9_nike_tech_gris_up_nico_1777388817.png
24	9	/media/images/products/9/9_nike_tech_gris_down_nico_1777388817.png
\.


--
-- Data for Name: imagenes_usuario; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.imagenes_usuario (id_imagen_usuario, id_usuario, ruta) FROM stdin;
\.


--
-- Data for Name: incidencias; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.incidencias (id_incidencia, id_usuario, tipo, fecha, estado_incidencia, descripcion) FROM stdin;
\.


--
-- Data for Name: pedidos; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.pedidos (id_pedido, id_usuario, estado, total, fecha, direccion, numero_piso) FROM stdin;
\.


--
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.productos (id_producto, nombre_producto, precio_venta, precio_original, precio_costo, stock, categoria, personalizable, nuevo, oferta) FROM stdin;
2	Camiseta Oversize Beige	34.99	49.99	12.50	120	Streetwear	f	t	t
4	Sudadera Básica	24.99	29.99	20.00	20	Streetwear	t	t	t
3	Camiseta Básica	19.99	29.99	7.00	150	Básico	t	f	t
5	Gorra Gucci	299.99	400.00	10.00	15	Gorras	f	f	t
7	Jersey JEFF EFN	67.00	\N	26.00	30	Jerseys	f	f	f
9	Nike Tech NICO	199.99	\N	20.00	200	Deporte	f	t	f
1	Vestido Midi de Lino	189.90	\N	70.00	60	Vestidos	f	t	f
\.


--
-- Data for Name: productos_personalizados; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.productos_personalizados (id_producto_personalizado, id_producto, id_talla, id_imagen_usuario, color, texto, ruta_imagen, posicion_xy) FROM stdin;
\.


--
-- Data for Name: productos_vendidos; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.productos_vendidos (id_producto_vendido, id_producto, id_pedido, id_talla, beneficio, cantidad, precio_venta) FROM stdin;
\.


--
-- Data for Name: tallas; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.tallas (id_talla, id_producto, talla, stock) FROM stdin;
4	2	L	35
5	2	XL	20
7	3	S	25
8	3	M	50
9	3	L	45
10	3	XL	25
11	3	XXL	5
14	4	S	5
15	4	M	5
16	4	L	5
17	4	XL	5
18	5	M	10
19	5	L	5
29	9	S	50
30	9	M	100
31	9	L	25
32	9	XL	25
24	1	S	0
12	1	M	20
13	1	L	10
3	2	M	40
6	2	XXL	0
2	2	S	15
21	7	S	10
22	7	M	10
23	7	L	10
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: customlab_user
--

COPY public.usuarios (id_usuario, nombre, apellidos, password, email, fecha_nacimiento, doble_factor, rol, secret_2fa) FROM stdin;
2	Moussa	Boudhafri Nijaoui	pbkdf2_sha256$1200000$3h3b5EOPbUh2ejLKFMMUHt$qoXBnS94T+WTl0oAB8cNMEx5cPn0126d0bPXvOfbFwQ=	24.moussa.boudhafri@insdanielblanxart.cat	2006-09-18	f	manager	\N
3	David	Juncosa Alegre	pbkdf2_sha256$1200000$beCEJAhYAoVaWWWwtqkkds$YZ7plk8s6ljEEK9Y8gOuoJGmZ9fFj7TKVeK5uiQsz90=	davidjuncosaalegre@gmail.com	2006-09-28	f	admin	\N
9	Raúl	García Magro	pbkdf2_sha256$1200000$Obr5tlamforVpBCvfGvAr6$Mp4rTErO3RzCrkN1kdjxuPGwn+CxXUTv/cbf0P8aSpg=	rgarci@insdanielblanxart.cat	\N	\N	cliente	\N
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 24, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: caracteristicas_id_caracteristica_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.caracteristicas_id_caracteristica_seq', 8, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 18, true);


--
-- Name: imagenes_productos_id_imagen_producto_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.imagenes_productos_id_imagen_producto_seq', 24, true);


--
-- Name: imagenes_usuario_id_imagen_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.imagenes_usuario_id_imagen_usuario_seq', 1, false);


--
-- Name: incidencias_id_incidencia_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.incidencias_id_incidencia_seq', 1, false);


--
-- Name: pedidos_id_pedido_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.pedidos_id_pedido_seq', 1, false);


--
-- Name: productos_id_producto_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.productos_id_producto_seq', 9, true);


--
-- Name: productos_personalizados_id_producto_personalizado_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.productos_personalizados_id_producto_personalizado_seq', 1, false);


--
-- Name: productos_vendidos_id_producto_vendido_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.productos_vendidos_id_producto_vendido_seq', 1, false);


--
-- Name: tallas_id_talla_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.tallas_id_talla_seq', 32, true);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: customlab_user
--

SELECT pg_catalog.setval('public.usuarios_id_usuario_seq', 9, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: caracteristicas caracteristicas_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.caracteristicas
    ADD CONSTRAINT caracteristicas_pkey PRIMARY KEY (id_caracteristica);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: usuarios email_unique; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT email_unique UNIQUE (email);


--
-- Name: imagenes_productos imagenes_productos_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.imagenes_productos
    ADD CONSTRAINT imagenes_productos_pkey PRIMARY KEY (id_imagen_producto);


--
-- Name: imagenes_usuario imagenes_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.imagenes_usuario
    ADD CONSTRAINT imagenes_usuario_pkey PRIMARY KEY (id_imagen_usuario);


--
-- Name: incidencias incidencias_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.incidencias
    ADD CONSTRAINT incidencias_pkey PRIMARY KEY (id_incidencia);


--
-- Name: pedidos pedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_pkey PRIMARY KEY (id_pedido);


--
-- Name: productos_personalizados productos_personalizados_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.productos_personalizados
    ADD CONSTRAINT productos_personalizados_pkey PRIMARY KEY (id_producto_personalizado);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id_producto);


--
-- Name: productos_vendidos productos_vendidos_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.productos_vendidos
    ADD CONSTRAINT productos_vendidos_pkey PRIMARY KEY (id_producto_vendido);


--
-- Name: tallas tallas_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.tallas
    ADD CONSTRAINT tallas_pkey PRIMARY KEY (id_talla);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: customlab_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: caracteristica_producto id_caracteristica_caracteristica_producto_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.caracteristica_producto
    ADD CONSTRAINT id_caracteristica_caracteristica_producto_fk FOREIGN KEY (id_caracteristica) REFERENCES public.caracteristicas(id_caracteristica) NOT VALID;


--
-- Name: productos_personalizados id_imagen_usuario_productos_personalizados_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.productos_personalizados
    ADD CONSTRAINT id_imagen_usuario_productos_personalizados_fk FOREIGN KEY (id_imagen_usuario) REFERENCES public.imagenes_usuario(id_imagen_usuario) NOT VALID;


--
-- Name: carrito id_prodcuto_carrito_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT id_prodcuto_carrito_fk FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto) NOT VALID;


--
-- Name: caracteristica_producto id_producto_caracteristica_producto_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.caracteristica_producto
    ADD CONSTRAINT id_producto_caracteristica_producto_fk FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto) NOT VALID;


--
-- Name: imagenes_productos id_producto_imagenes_productos_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.imagenes_productos
    ADD CONSTRAINT id_producto_imagenes_productos_fk FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto);


--
-- Name: productos_personalizados id_producto_productos_personalizados_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.productos_personalizados
    ADD CONSTRAINT id_producto_productos_personalizados_fk FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto) NOT VALID;


--
-- Name: tallas id_producto_tallas_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.tallas
    ADD CONSTRAINT id_producto_tallas_fk FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto);


--
-- Name: carrito id_talla_carrito_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT id_talla_carrito_fk FOREIGN KEY (id_talla) REFERENCES public.tallas(id_talla) NOT VALID;


--
-- Name: productos_personalizados id_talla_productos_personalizados_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.productos_personalizados
    ADD CONSTRAINT id_talla_productos_personalizados_fk FOREIGN KEY (id_talla) REFERENCES public.tallas(id_talla) NOT VALID;


--
-- Name: carrito id_usuario_carrito_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT id_usuario_carrito_fk FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- Name: imagenes_usuario id_usuario_imagenes_usuario_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.imagenes_usuario
    ADD CONSTRAINT id_usuario_imagenes_usuario_fk FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- Name: incidencias id_usuario_incidencias_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.incidencias
    ADD CONSTRAINT id_usuario_incidencias_fk FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- Name: pedidos id_usuario_pedidos_fk; Type: FK CONSTRAINT; Schema: public; Owner: customlab_user
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT id_usuario_pedidos_fk FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- PostgreSQL database dump complete
--

\unrestrict sbLr80DozPdCDfQXVk4soq7yuxR1O0nybYrbzgYmcsqvpi6OwVmrP3RqmPgW4oj

